// Smoke test for the first shadcn component. Proves the whole
// integration pipeline works end-to-end:
//   * `@/` alias resolves (the source imports `@/lib/utils`)
//   * Tailwind v4 utilities applied via `cva` variants land on the
//     rendered DOM
//   * Radix `Slot` primitive (when `asChild` is set) doesn't break
//   * RTL `userEvent` clicks bubble up to React onClick
//
// We deliberately don't test every variant — shadcn's components are
// upstream code we don't own line-by-line; pinning each variant would
// add maintenance burden whenever we run `npx shadcn add --overwrite`.
// One render-and-click is enough to know the wiring is alive.

import { describe, expect, it, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { Button } from "./button";

describe("<Button />", () => {
  it("renders its children", () => {
    render(<Button>Create exploit</Button>);
    expect(screen.getByRole("button", { name: "Create exploit" })).toBeInTheDocument();
  });

  it("applies the default variant's primary background utility class", () => {
    // `bg-primary` is generated by Tailwind from our `--primary`
    // token; presence in the className list proves cva variants and
    // Tailwind utility generation both work.
    render(<Button>X</Button>);
    expect(screen.getByRole("button")).toHaveClass("bg-primary");
  });

  it("switches utilities when variant=secondary", () => {
    render(<Button variant="secondary">X</Button>);
    expect(screen.getByRole("button")).toHaveClass("bg-secondary");
  });

  it("fires onClick when clicked", async () => {
    const onClick = vi.fn();
    render(<Button onClick={onClick}>Click me</Button>);
    await userEvent.click(screen.getByRole("button"));
    expect(onClick).toHaveBeenCalledOnce();
  });

  it("respects the disabled prop and does not fire onClick", async () => {
    const onClick = vi.fn();
    render(
      <Button onClick={onClick} disabled>
        Click me
      </Button>,
    );
    await userEvent.click(screen.getByRole("button"));
    expect(onClick).not.toHaveBeenCalled();
  });

  it("supports asChild — composes className onto the wrapped element", () => {
    // shadcn's `asChild` swaps the underlying tag via Radix `Slot`.
    // Useful for `<Button asChild><a href="…">…</a></Button>` patterns.
    render(
      <Button asChild>
        <a href="/somewhere">go</a>
      </Button>,
    );
    const link = screen.getByRole("link", { name: "go" });
    expect(link).toBeInTheDocument();
    expect(link).toHaveClass("bg-primary");
  });
});
