from dataclasses import dataclass, field
from operator import add
from typing import Annotated, Any, Literal

ALLOWED_SCOPE_ROLES: tuple[str, ...] = (
    "dependency",
    "injection",
    "owasp",
)


@dataclass
class RepoFile:
    """A single file fetched from a GitHub repo tree for repo-mode review.

    `content` is the decoded UTF-8 source (or empty string for binary /
    oversize files filtered out by GitHubClient before reaching reviewers).
    `path` is repo-relative.
    """

    path: str
    content: str
    size: int = 0


@dataclass
class ReviewRequest:
    """Unified request shape for both PR and repo reviews.

    `mode` discriminates which fields are populated. The dataclass keeps a
    single shape (rather than a union of two) so downstream code can access
    common fields (`author`, `scope`) without dispatching, and per-mode
    fields stay empty in the other mode.
    """

    mode: Literal["pr", "repo"] = "pr"
    # PR-mode fields
    pr_url: str = ""
    diff: str = ""
    files_changed: list[str] = field(default_factory=list)
    # Repo-mode fields
    repo_url: str = ""
    ref: str = "HEAD"
    repo_files: list[RepoFile] = field(default_factory=list)
    # Absolute path to the local snapshot (result of `git clone --depth=1`)
    # where reviewers read file contents from. Populated by
    # `_run_repo_review` before invoking the graph; empty for PR-mode runs.
    snapshot_dir: str = ""
    # Common
    author: str = ""
    scope: list[str] = field(default_factory=list)  # roles to run; empty = all


@dataclass
class AgentReview:
    agent_name: str
    role: str
    findings: list[dict[str, Any]]
    summary: str
    severity: str  # critical | major | minor | info
    passed: bool


@dataclass
class ExploitProposal:
    """Phase C — outcome of an exploit-proposal cycle for a single finding.

    Status taxonomy:
      - `approved`               : human approved → artifact populated with PoC text
      - `declined`               : human explicitly declined → artifact empty
      - `skipped_low_confidence` : agent self-rated unable to reliably craft a PoC,
                                   no human prompt issued, no artifact
      - `timeout_declined`       : human did not respond within the timeout window,
                                   default-declined
      - `skipped_cap_reached`    : the 3-cycle iteration cap was hit before this
                                   finding's turn; no LLM call, no human prompt
    """

    finding_id: str
    role: str
    severity: str
    proposal_text: str
    status: str
    artifact: str = ""
    confidence: int = 0
    # Where the artifact ends up once `status == "approved"`:
    #   "embed" — inlined into the main `reports/<thread_id>.md` (default).
    #   "file"  — written as a sibling `reports/<thread_id>.exploit.<finding_id>.md`,
    #             linked from the main report.
    # The chat exposes both via buttons; `_parse_resume` parses the trailing
    # token from the user's reply.
    save_mode: Literal["embed", "file"] = "embed"


@dataclass
class ValidationVerdict:
    """Outcome of the request validator (Phase A of the workflow redesign).

    Category is one of:
      empty_diff | docs_only | autogenerated | out_of_scope   (pure-code prefilter)
      trolling | accepted | other                              (LLM judge)
    Stable category labels let `notify_rejection` use template-based comments
    and let tests assert on category instead of fragile reason prose.
    """

    accepted: bool
    category: str
    reason: str


@dataclass
class ReviewState:
    request: ReviewRequest | None = None
    # Thread identifier (LangGraph checkpoint key + chat session id + report
    # filename in repo-mode). Populated by `_run_review` / `_run_repo_review`
    # before invoking the graph; nodes that need to write per-thread files
    # (e.g. CoordinatorAgent in repo-mode) read it from here.
    thread_id: str = ""
    # Validator verdict; None means "validator hasn't run yet". Reject path
    # reads category/reason to compose the rejection comment.
    validation: ValidationVerdict | None = None
    # `add` reducer — TWO reasons we keep it:
    #
    #   1. PARALLEL writers (the real concurrency case). The three security
    #      agents (dependency / injection / owasp) run in parallel after
    #      `validate_request`; each returns {"agent_reviews": [one]} and
    #      LangGraph's reducer concatenates without racing. Without the
    #      reducer the last writer would clobber the other two.
    #
    #   2. INCREMENTAL accumulation across cycles. On Phase B reruns the
    #      reviewers fire again and each appends a fresh entry — the
    #      reducer keeps the history, `ReportRenderer.render_review`
    #      dedupes by role keeping the latest pass.
    #
    # Both reasons apply to this field. Don't remove without rewriting
    # every reviewer node to read+merge before returning.
    agent_reviews: Annotated[list[AgentReview], add] = field(default_factory=list)
    # Phase B — human-in-the-loop re-review cycle:
    cycle_count: int = 0  # 0 = first pass; incremented when human approves a rerun
    extra_context: str = ""  # human's clarification spliced into the next reviewer pass
    last_human_answer: str = ""  # raw resume payload from the most recent interrupt
    # Phase C — exploit-proposal branch. `add` reducer is for INCREMENTAL
    # accumulation only — the topology serialises `process_proposal` via
    # `route_after_proposal`, so there's never a parallel writer for this
    # field. The reducer is what lets each node return
    # {"exploit_proposals": [one_new]} instead of having to read the full
    # list, append, and return the whole thing. Keep it; without it every
    # node would need a read-modify-write boilerplate.
    exploit_proposals: Annotated[list[ExploitProposal], add] = field(default_factory=list)
    # RAG — past similar findings retrieved by `PastContextAgent` before
    # the security-reviewer fan-out. Single writer (`past_context` node),
    # so NO reducer here — last write wins. `dict[role, list[finding-dict]]`.
    # Empty dict means "no past findings retrieved" — could be a fresh
    # repo, an embedder failure (fail-soft), or RAG disabled by config.
    past_findings_by_role: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    final_report: str = ""
    pr_comment_id: int | None = None
    error: str = ""
    completed: bool = False
