"""A.3 — CoordinatorAgent.notify_rejection posts a category-templated PR comment
and mirrors publish-path contract (sets completed + pr_comment_id)."""

import pytest

from src.agents.coordinator import CoordinatorAgent
from src.graph.state import ReviewRequest, ReviewState, ValidationVerdict


def _state(category: str, reason: str = "test reason") -> ReviewState:
    return ReviewState(
        request=ReviewRequest(
            pr_url="https://github.com/o/r/pull/1",
            diff="d",
            files_changed=["x"],
            author="u",
        ),
        validation=ValidationVerdict(accepted=False, category=category, reason=reason),
    )


@pytest.mark.parametrize(
    "category, expected_phrase",
    [
        ("empty_diff", "empty"),
        ("docs_only", "documentation"),
        ("autogenerated", "generated"),
        ("out_of_scope", "scope"),
        ("trolling", "review"),
    ],
)
async def test_notify_rejection_posts_category_template_comment(category, expected_phrase, mocker):
    github = mocker.AsyncMock()
    github.post_pr_comment.return_value = 12345
    coordinator = CoordinatorAgent(github=github)

    state = _state(category)
    update = await coordinator.notify_rejection(state)

    github.post_pr_comment.assert_awaited_once()
    _pr_url, body = github.post_pr_comment.await_args.args
    assert expected_phrase.lower() in body.lower()
    assert update["pr_comment_id"] == 12345
    assert update["completed"] is True


async def test_notify_rejection_records_error_on_failure(mocker):
    github = mocker.AsyncMock()
    github.post_pr_comment.side_effect = RuntimeError("401 unauthorized")
    coordinator = CoordinatorAgent(github=github)

    update = await coordinator.notify_rejection(_state("empty_diff"))

    assert update["completed"] is True
    assert "401 unauthorized" in update["error"]
