"""Pure-render module for review markdown.

Split out of `CoordinatorAgent` (which was a god-node owning rendering
AND every I/O surface: disk write, GitHub comment, multi-node graph
orchestration). The renderer has ZERO I/O — it takes the data and
returns a string. `CoordinatorAgent` still owns the disk-write / GitHub
posting; it just delegates the "what does the report look like" question
here.

Surfaces:
  * `render_review(reviews, exploit_proposals, request, thread_id) -> str`
    — the main `<thread_id>.md` body.
  * `render_rejection(verdict) -> str` — the templated "review skipped"
    body keyed by `verdict.category`. Falls back to a generic template
    on unknown categories; tolerates `verdict=None` (validator skipped).
  * `render_exploit_sibling(ep, thread_id) -> str` — the standalone
    Markdown written to `<thread_id>.exploit.<finding_id>.md` for
    `save_mode="file"` artifacts.
  * `exploit_artifact_filename(thread_id, finding_id) -> str` — stable
    filename for the sibling file. Static method on the class so the
    coordinator and JS UI can reference the same naming.

Module-level constants (`_ROLE_LABELS`, `_SEVERITY_RANK`,
`_STATUS_LABELS`, `_REJECTION_TEMPLATES`) live here too — they were
already private to coordinator.py but the new home is where the
rendering itself lives.
"""

from __future__ import annotations

from src.agents.exploit_proposal import EXPLOIT_DISCLAIMER
from src.graph.state import AgentReview, ExploitProposal, ValidationVerdict

# Display labels for the per-role section headings — keep the keys
# aligned with `ALLOWED_SCOPE_ROLES` in `src/graph/state.py`.
_ROLE_LABELS = {
    "dependency": "Dependencies",
    "injection": "Injection",
    "owasp": "OWASP Top 10",
}

# Numeric ordering for "overall severity = max(per-reviewer severity)".
# Higher rank wins.
_SEVERITY_RANK = {"critical": 3, "major": 2, "minor": 1, "info": 0}

# Per-status display text in the "Not generated" exploit-section list.
_STATUS_LABELS = {
    "declined": "declined by reviewer",
    "skipped_low_confidence": "skipped (low confidence)",
    "timeout_declined": "timeout — default-declined",
    "skipped_cap_reached": "skipped (3-cycle cap reached)",
}

# Category-keyed rejection-notice templates. `{reason}` is filled with
# `ValidationVerdict.reason`. Anything not in this map falls back to
# `_GENERIC_REJECTION` below.
_REJECTION_TEMPLATES = {
    "empty_diff": (
        "## Security review skipped\n\n"
        "The diff is empty (no add/remove payload). Nothing to review.\n\n"
        "_{reason}_"
    ),
    "docs_only": (
        "## Security review skipped\n\n"
        "All changed files are documentation. No code paths to analyze.\n\n"
        "_{reason}_"
    ),
    "autogenerated": (
        "## Security review skipped\n\n"
        "All changed files are auto-generated (lockfiles, minified bundles, "
        "generated stubs). Inspect the source diff instead.\n\n"
        "_{reason}_"
    ),
    "out_of_scope": (
        "## Security review skipped\n\n"
        "This PR is out of scope for automated review (diff too large or "
        "structure unsupported).\n\n"
        "_{reason}_"
    ),
    "trolling": (
        "## Security review declined\n\n"
        "The request does not look like a legitimate review target.\n\n"
        "_{reason}_"
    ),
    "empty_repo": (
        "## Security review skipped\n\n"
        "The repository tree contains no reviewable files at the requested ref.\n\n"
        "_{reason}_"
    ),
    "oversized_repo": (
        "## Security review skipped\n\n"
        "The repository is too large for a single-pass review. Narrow the "
        "scope (specific subdirectories or a smaller ref) and try again.\n\n"
        "_{reason}_"
    ),
}

_GENERIC_REJECTION = (
    "## Security review skipped\n\n"
    "The reviewer declined to process this PR.\n\n"
    "_{reason}_"
)


class ReportRenderer:
    """Pure Markdown renderer. No filesystem, no LangGraph, no network.

    Instantiate once and call as many times as you like — there's no
    per-render state. The class shape (rather than module-level
    functions) is a hook for future per-deployment variations (e.g.
    GitHub-flavoured vs GitLab-flavoured Markdown, branded headers).
    """

    # ── public API ────────────────────────────────────────────────────

    def render_review(
        self,
        reviews: list[AgentReview],
        exploit_proposals: list[ExploitProposal] | None = None,
        *,
        request=None,
        thread_id: str = "",
    ) -> str:
        """Main review markdown. See module docstring for the contract."""
        if not reviews:
            return (
                "## Security review\n\n"
                + _render_target_header(request)
                + "(no reviewers ran)"
            )
        # Dedup by role keeping the latest entry per role. Across re-review
        # cycles `agent_reviews` accumulates one set of reviews per pass;
        # only the most recent pass per role should surface in the report.
        latest_by_role: dict[str, AgentReview] = {}
        for r in reviews:
            latest_by_role[r.role] = r
        reviews = list(latest_by_role.values())
        overall = max(
            (_SEVERITY_RANK.get(r.severity, 0) for r in reviews),
            default=0,
        )
        header_severity = _rank_to_label(overall)
        target = _render_target_header(request)
        lines = [
            "## Security review",
            "",
            *([target.rstrip("\n")] if target else []),
            *([""] if target else []),
            f"**Overall severity:** {header_severity}",
            "",
        ]
        for r in reviews:
            label = _ROLE_LABELS.get(r.role, r.role)
            lines.append(f"### {label} — {r.severity}")
            lines.append("")
            lines.append(r.summary or "_(no summary)_")
            if r.findings:
                lines.append("")
                for f in r.findings:
                    lines.append(f"- {_format_finding(f)}")
            lines.append("")

        if exploit_proposals:
            lines.extend(_render_exploit_section(exploit_proposals, thread_id=thread_id))

        return "\n".join(lines).rstrip() + "\n"

    def render_rejection(self, verdict: ValidationVerdict | None) -> str:
        """Templated "review skipped" body. `verdict=None` (validator
        never ran) → safe fallback string, never raises."""
        if verdict is None:
            return "## Security review skipped\n\nValidator state missing.\n"
        template = _REJECTION_TEMPLATES.get(verdict.category, _GENERIC_REJECTION)
        return template.format(reason=verdict.reason or "(no reason given)")

    def render_exploit_sibling(self, ep: ExploitProposal, *, thread_id: str = "") -> str:
        return _render_exploit_sibling(ep, thread_id)

    @staticmethod
    def exploit_artifact_filename(thread_id: str, finding_id: str) -> str:
        """Stable filename for a save_mode=file artifact. `unknown.exploit…`
        when thread_id is empty — predictable fallback so the link in
        the main report never points at an undefined name."""
        safe_tid = thread_id or "unknown"
        return f"{safe_tid}.exploit.{finding_id}.md"


# ── module-level helpers (kept private; also re-exported by coordinator
# for back-compat with tests that imported the originals) ──────────────


def _render_target_header(request) -> str:
    """One-line "**Repository:** ..." / "**Pull request:** ..." header.

    Returned with a trailing newline so callers can splice it directly
    into the report's leading paragraphs; empty string when `request` is
    None (e.g. legacy callers, tests).
    """
    if request is None:
        return ""
    mode = getattr(request, "mode", "pr")
    if mode == "repo":
        repo_url = getattr(request, "repo_url", "")
        ref = getattr(request, "ref", "") or "HEAD"
        if repo_url:
            return f"**Repository:** {repo_url} (ref `{ref}`)\n"
    pr_url = getattr(request, "pr_url", "")
    if pr_url:
        return f"**Pull request:** {pr_url}\n"
    return ""


def _rank_to_label(rank: int) -> str:
    for label, r in _SEVERITY_RANK.items():
        if r == rank:
            return label
    return "info"


def _render_exploit_section(
    proposals: list[ExploitProposal],
    *,
    thread_id: str = "",
) -> list[str]:
    """Render the Phase C exploit-proposal section.

    `save_mode` controls how an approved proposal is rendered:
      `embed` (default)  → proposal text + `<details>`-wrapped artifact
                           inlined right here in the main report.
      `file`             → proposal text + a link to the sibling artifact
                           file `./<thread_id>.exploit.<finding_id>.md`.

    Declined / skipped / timeout entries are listed compactly regardless
    of save_mode.
    """
    approved = [p for p in proposals if p.status == "approved"]
    other = [p for p in proposals if p.status != "approved"]

    lines = [
        "## Exploit proposals",
        "",
        f"> {EXPLOIT_DISCLAIMER}",
        "",
    ]

    for p in approved:
        label = _ROLE_LABELS.get(p.role, p.role)
        save_mode = getattr(p, "save_mode", "embed") or "embed"
        suffix = " — saved as separate file" if save_mode == "file" else ""
        lines.append(
            f"### {label} — `{p.finding_id}` ({p.severity}, approved{suffix})"
        )
        lines.append("")
        lines.append(p.proposal_text or "_(no proposal text)_")

        if save_mode == "file":
            sibling = ReportRenderer.exploit_artifact_filename(thread_id, p.finding_id)
            lines.append("")
            lines.append(
                f"Exploit details saved to [`{sibling}`](./{sibling})."
            )
        elif p.artifact:
            lines.append("")
            lines.append("<details><summary>PoC artifact</summary>")
            lines.append("")
            lines.append("```")
            lines.append(p.artifact)
            lines.append("```")
            lines.append("")
            lines.append("</details>")
        lines.append("")

    if other:
        lines.append("### Not generated")
        lines.append("")
        for p in other:
            status_label = _STATUS_LABELS.get(p.status, p.status)
            label = _ROLE_LABELS.get(p.role, p.role)
            lines.append(f"- `{p.finding_id}` — {label} ({p.severity}) — {status_label}")
        lines.append("")

    return lines


def _render_exploit_sibling(ep: ExploitProposal, thread_id: str) -> str:
    """Standalone Markdown for a single `save_mode="file"` artifact.

    Stored as `<thread_id>.exploit.<finding_id>.md` next to the main
    report. Carries the proposal text, the LLM-generated artifact, plus
    a back-link to the main `<thread_id>.md`.
    """
    role_label = _ROLE_LABELS.get(ep.role, ep.role)
    main_link = f"./{thread_id}.md" if thread_id else None
    parts = [
        f"# Exploit PoC — {role_label} finding `{ep.finding_id}`",
        "",
        f"**Severity:** {ep.severity}",
        "",
        f"> {EXPLOIT_DISCLAIMER}",
        "",
    ]
    if main_link:
        parts.append(f"Back to [main report](./{thread_id}.md).")
        parts.append("")
    parts.append("## Proposal")
    parts.append("")
    parts.append(ep.proposal_text or "_(no proposal text)_")
    parts.append("")
    parts.append("## Artifact")
    parts.append("")
    parts.append("```")
    parts.append(ep.artifact or "(empty)")
    parts.append("```")
    parts.append("")
    return "\n".join(parts)


def _format_finding(finding: dict) -> str:
    location = ""
    if finding.get("file"):
        location = finding["file"]
        if finding.get("line"):
            location += f":{finding['line']}"
    category = finding.get("category") or finding.get("package")
    severity = finding.get("severity", "info")
    issue = finding.get("issue") or finding.get("raw") or ""
    parts = [p for p in (location, category, f"[{severity}]") if p]
    prefix = " — ".join(parts)
    return f"{prefix} {issue}".strip()
