"""Request validator — Phase A of the workflow redesign.

Two-stage check:
  1. Pure-code prefilter: deterministic rules for the obvious cases (empty diff,
     whitespace-only, docs-only, autogenerated, oversized). No LLM call.
  2. LLM judge: anything that survives the prefilter goes through an LLM that
     returns strict JSON {verdict, category, reason}. If the LLM response
     can't be parsed, default to **accept** — we don't want LLM flakiness to
     block legitimate review work.

The validator writes a `ValidationVerdict` into `state.validation`; the graph's
conditional edge after `validate_request` reads `verdict.accepted` to route
between the reviewer fan-out and `notify_rejection`.
"""

import json
import re

from src.graph.state import ReviewRequest, ReviewState, ValidationVerdict
from src.models.factory import ModelFactory
from src.utils.config import settings
from src.utils.llm_parsing import strip_thinking_trace

_DEFAULT_MAX_DIFF_CHARS = 200_000
_DEFAULT_MODEL = "claude-sonnet-4-6"

_DOC_EXTENSIONS = frozenset({"md", "rst", "txt", "adoc"})
_DOC_FILENAMES = frozenset({"LICENSE", "CHANGELOG", "AUTHORS", "CONTRIBUTORS", "NOTICE"})
_DOC_PATH_PREFIXES = ("docs/", "doc/")

_AUTOGEN_FILE_PATTERNS = (
    re.compile(r"(^|/)package-lock\.json$"),
    re.compile(r"(^|/)yarn\.lock$"),
    re.compile(r"(^|/)poetry\.lock$"),
    re.compile(r"(^|/)Cargo\.lock$"),
    re.compile(r"(^|/)go\.sum$"),
    re.compile(r"\.min\.(js|css)$"),
    re.compile(r"\.pb\.go$"),
    re.compile(r"_pb2\.py$"),
    re.compile(r"(^|/)(dist|build|gen)/"),
)
_AUTOGEN_MARKERS = ("@generated", "DO NOT EDIT")

_LLM_PROMPT_TEMPLATE = """You are a request validator for a security code-review service.

Decide if this Pull Request is a legitimate code change worth a security review,
or junk / trolling / unrelated noise. The diff has already passed cheap
deterministic checks (it's not empty, not docs-only, not autogenerated, not
oversized) — your job is the semantic judgement only.

Respond with a single JSON object, no prose, no fenced code block:
{{"verdict": "accept" | "reject",
  "category": "accepted" | "trolling" | "other",
  "reason": "one-sentence explanation"}}

When uncertain, default to accept. Only reject if the PR is clearly
nonsense (joke commits, profanity-only changes, deliberate sabotage).

PR: {pr_url}
Author: {author}
Files changed: {files}

Diff (truncated to first 8000 chars):
{diff}
"""

# Anything `+` or `-` line that isn't the file-header `+++ a/...` / `--- b/...`
# counts as a real payload. Context lines start with a space.
_HEADER_PREFIXES = ("+++", "---")


def _diff_has_payload(diff: str) -> bool:
    for line in diff.splitlines():
        if line.startswith(_HEADER_PREFIXES):
            continue
        if line.startswith(("+", "-")):
            return True
    return False


def _is_doc_file(path: str) -> bool:
    if path in _DOC_FILENAMES:
        return True
    if path.startswith(_DOC_PATH_PREFIXES):
        return True
    return "." in path and path.rsplit(".", 1)[-1].lower() in _DOC_EXTENSIONS


def _is_autogen_file(path: str) -> bool:
    return any(p.search(path) for p in _AUTOGEN_FILE_PATTERNS)


def _diff_has_autogen_marker(diff: str) -> bool:
    return any(marker in diff for marker in _AUTOGEN_MARKERS)


class RequestValidator:
    """Stage 1 (pure-code) + stage 2 (LLM judge) gate before the security reviewers."""

    def __init__(self, model_name: str | None = None, max_diff_chars: int | None = None):
        self.model_name = model_name or _DEFAULT_MODEL
        self.model = ModelFactory.get(self.model_name)
        self.max_diff_chars = (
            max_diff_chars
            if max_diff_chars is not None
            else getattr(settings, "VALIDATOR_MAX_DIFF_CHARS", _DEFAULT_MAX_DIFF_CHARS)
        )

    async def run(self, state: ReviewState) -> dict:
        request = state.request
        if request is None:
            return {
                "validation": ValidationVerdict(
                    accepted=False, category="other", reason="missing request"
                )
            }

        if request.mode == "repo":
            # Repo-mode has no diff to inspect and no notion of "trolling":
            # only the structural checks (empty tree / oversized) apply.
            return {"validation": self._prefilter_repo(request)}

        verdict = self._prefilter(request)
        if verdict is None:
            verdict = await self._llm_judge(request)
        return {"validation": verdict}

    def _prefilter_repo(self, request: ReviewRequest) -> ValidationVerdict:
        """Pure-code rules for repo-mode requests.

        - Empty tree     → `empty_repo`
        - Above hard cap → `oversized_repo`
        - Anything else  → accept (per-reviewer whitelist filtering happens
                           downstream in BaseReviewer._run_repo)
        """
        if not request.repo_files:
            return ValidationVerdict(
                accepted=False,
                category="empty_repo",
                reason="repository tree contains no reviewable files",
            )
        hard_cap = getattr(settings, "MAX_REPO_FILES_HARD", 5000)
        if len(request.repo_files) > hard_cap:
            return ValidationVerdict(
                accepted=False,
                category="oversized_repo",
                reason=(
                    f"repository has {len(request.repo_files)} files, "
                    f"exceeds hard cap of {hard_cap}"
                ),
            )
        return ValidationVerdict(
            accepted=True,
            category="accepted",
            reason=f"{len(request.repo_files)} files queued for per-specialist review",
        )

    def _prefilter(self, request: ReviewRequest) -> ValidationVerdict | None:
        if not request.diff.strip() or not _diff_has_payload(request.diff):
            return ValidationVerdict(
                accepted=False,
                category="empty_diff",
                reason="diff has no add/remove payload lines",
            )

        if len(request.diff) > self.max_diff_chars:
            return ValidationVerdict(
                accepted=False,
                category="out_of_scope",
                reason=f"diff exceeds {self.max_diff_chars} char limit ({len(request.diff)} chars)",
            )

        files = request.files_changed
        if files and all(_is_autogen_file(f) for f in files):
            return ValidationVerdict(
                accepted=False,
                category="autogenerated",
                reason="all changed files match auto-generated patterns",
            )
        if _diff_has_autogen_marker(request.diff):
            return ValidationVerdict(
                accepted=False,
                category="autogenerated",
                reason="diff contains @generated / DO NOT EDIT marker",
            )

        if files and all(_is_doc_file(f) for f in files):
            return ValidationVerdict(
                accepted=False,
                category="docs_only",
                reason="all changed files are documentation",
            )

        return None  # fall through to the LLM judge

    async def _llm_judge(self, request: ReviewRequest) -> ValidationVerdict:
        prompt = _LLM_PROMPT_TEMPLATE.format(
            pr_url=request.pr_url,
            author=request.author,
            files=", ".join(request.files_changed) or "(none)",
            diff=request.diff[:8000],
        )
        response = await self.model.ainvoke(prompt)
        return _parse_llm_response(response.content)


def _parse_llm_response(content: str) -> ValidationVerdict:
    """Strict JSON expected. On any parse failure, default to accept.

    Hybrid-thinking models (Qwen3.6-27B, DeepSeek R1, o1-style) wrap the
    actual JSON in a long `</think>`-fenced chain-of-thought trace.
    Without the strip below, every response from such a model falls into
    the default-accept branch — which would mask a real REJECT verdict.
    Same strip pattern as `BaseReviewer._parse_response` (PR #7).
    """
    content = strip_thinking_trace(content)
    try:
        data = json.loads(content.strip())
        verdict = data.get("verdict", "").lower()
        category = data.get("category", "")
        reason = data.get("reason", "")
        if verdict == "reject":
            return ValidationVerdict(
                accepted=False,
                category=category or "other",
                reason=reason or "LLM rejected without specific reason",
            )
        return ValidationVerdict(
            accepted=True,
            category=category or "accepted",
            reason=reason or "LLM accepted",
        )
    except (json.JSONDecodeError, ValueError, AttributeError):
        return ValidationVerdict(
            accepted=True,
            category="accepted",
            reason="LLM response unparseable; defaulting to accept to avoid blocking",
        )
