"""Unit tests for RequestValidator: pure-code prefilter + LLM-judge fallback.

A.1 of the workflow redesign. Pure-code rules handle the trivial cases
(empty / whitespace / docs-only / autogen / oversized) without an LLM call;
anything that survives the prefilter falls through to the LLM judge for a
trolling-vs-legitimate decision. On LLM parse error we default to accept —
we don't want LLM flakiness to block legitimate review work.
"""

import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from src.agents.validator import RequestValidator
from src.graph.state import ReviewRequest, ReviewState, ValidationVerdict


def _request(*, diff: str = "", files: list[str] | None = None) -> ReviewRequest:
    return ReviewRequest(
        pr_url="https://github.com/o/r/pull/1",
        diff=diff,
        files_changed=files or [],
        author="x",
    )


# ── A.1.1–A.1.6: pure-code prefilter (no LLM call) ───────────────────────────


async def test_empty_diff_rejected_as_empty_diff():
    mock_model = AsyncMock()
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(ReviewState(request=_request(diff="", files=["a.py"])))

    verdict = update["validation"]
    assert isinstance(verdict, ValidationVerdict)
    assert verdict.accepted is False
    assert verdict.category == "empty_diff"
    mock_model.ainvoke.assert_not_awaited()


async def test_whitespace_only_diff_rejected_as_empty_diff():
    # Diff has file headers + a hunk but no `+`/`-` payload lines.
    diff = (
        "diff --git a/x.py b/x.py\n"
        "--- a/x.py\n"
        "+++ b/x.py\n"
        "@@ -1,3 +1,3 @@\n"
        " context line one\n"
        " context line two\n"
        " context line three\n"
    )
    mock_model = AsyncMock()
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(ReviewState(request=_request(diff=diff, files=["x.py"])))

    assert update["validation"].accepted is False
    assert update["validation"].category == "empty_diff"
    mock_model.ainvoke.assert_not_awaited()


async def test_docs_only_pr_rejected():
    mock_model = AsyncMock()
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(
            ReviewState(
                request=_request(
                    diff="diff --git a/README.md b/README.md\n+new line\n",
                    files=["README.md", "docs/intro.md", "CHANGELOG"],
                )
            )
        )

    assert update["validation"].accepted is False
    assert update["validation"].category == "docs_only"
    mock_model.ainvoke.assert_not_awaited()


async def test_mixed_docs_and_code_passes_prefilter():
    """Guard: docs-only check must not over-trigger on mixed PRs."""
    mock_model = AsyncMock()
    mock_model.ainvoke.return_value = MagicMock(
        content=json.dumps({"verdict": "accept", "category": "accepted", "reason": "ok"})
    )
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(
            ReviewState(
                request=_request(
                    diff="diff --git a/x.py b/x.py\n+def f(): pass\n",
                    files=["README.md", "src/auth/service.py"],
                )
            )
        )

    mock_model.ainvoke.assert_awaited()
    assert update["validation"].accepted is True


@pytest.mark.parametrize(
    "files, diff",
    [
        (["package-lock.json"], "diff --git a/package-lock.json b/package-lock.json\n+{}\n"),
        (["app.min.js"], "diff --git a/app.min.js b/app.min.js\n+x\n"),
        (["proto/gen.pb.go"], "diff --git a/proto/gen.pb.go b/proto/gen.pb.go\n+x\n"),
        (["src/x.py"], "diff --git a/src/x.py b/src/x.py\n+// @generated\n+def f(): pass\n"),
        (["src/x.py"], "diff --git a/src/x.py b/src/x.py\n+// DO NOT EDIT\n+def f(): pass\n"),
    ],
)
async def test_autogen_files_or_markers_rejected(files, diff):
    mock_model = AsyncMock()
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(ReviewState(request=_request(diff=diff, files=files)))

    assert update["validation"].accepted is False
    assert update["validation"].category == "autogenerated"
    mock_model.ainvoke.assert_not_awaited()


async def test_oversized_diff_rejected_as_out_of_scope():
    big_diff = "diff --git a/x.py b/x.py\n+payload\n" + ("x" * 300_000)
    mock_model = AsyncMock()
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator(max_diff_chars=200_000)
        update = await validator.run(ReviewState(request=_request(diff=big_diff, files=["x.py"])))

    assert update["validation"].accepted is False
    assert update["validation"].category == "out_of_scope"
    mock_model.ainvoke.assert_not_awaited()


# ── A.1.7–A.1.10: LLM judge path ─────────────────────────────────────────────


async def test_normal_code_passes_prefilter_and_falls_through_to_llm():
    mock_model = AsyncMock()
    mock_model.ainvoke.return_value = MagicMock(
        content=json.dumps({"verdict": "accept", "category": "accepted", "reason": "looks legit"})
    )
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(
            ReviewState(
                request=_request(
                    diff="diff --git a/src/x.py b/src/x.py\n+def safe(): pass\n",
                    files=["src/x.py"],
                )
            )
        )

    mock_model.ainvoke.assert_awaited_once()
    assert update["validation"].accepted is True
    assert update["validation"].category == "accepted"


async def test_llm_judge_rejects_trolling():
    mock_model = AsyncMock()
    mock_model.ainvoke.return_value = MagicMock(
        content=json.dumps(
            {"verdict": "reject", "category": "trolling", "reason": "obvious joke commit"}
        )
    )
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(
            ReviewState(
                request=_request(
                    diff="diff --git a/x.py b/x.py\n+# lol just kidding\n",
                    files=["x.py"],
                )
            )
        )

    assert update["validation"].accepted is False
    assert update["validation"].category == "trolling"
    assert "obvious joke commit" in update["validation"].reason


async def test_llm_judge_fallback_on_parse_error_defaults_to_accept():
    """LLM flakiness must not block legitimate review work — default accept."""
    mock_model = AsyncMock()
    mock_model.ainvoke.return_value = MagicMock(content="not json at all, just some prose")
    with patch("src.agents.validator.ModelFactory.get", return_value=mock_model):
        validator = RequestValidator()
        update = await validator.run(
            ReviewState(
                request=_request(
                    diff="diff --git a/x.py b/x.py\n+def f(): pass\n",
                    files=["src/x.py"],
                )
            )
        )

    assert update["validation"].accepted is True
    assert update["validation"].category == "accepted"
